version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
       - dotnet build src/WeatherForecast.csproj
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - /**/*
  discard-paths: yes
